export const S = {
    mContainer: { maxWidth: 480, margin: '0 auto', minHeight: '100vh', background: '#f5f5f5', paddingBottom: 80 },
    dLayout: { display: 'flex', minHeight: '100vh', background: '#f0f2f5' },
    dSidebar: { width: 260, background: '#1e40af', color: '#fff', padding: '24px 16px', display: 'flex', flexDirection: 'column', gap: 8, position: 'fixed', top: 0, left: 0, height: '100vh', overflowY: 'auto' },
    dMain: { marginLeft: 260, flex: 1, padding: 24 },
    dHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
    dTitle: { fontSize: 24, fontWeight: 'bold', color: '#1e293b' },
    dTable: { width: '100%', borderCollapse: 'collapse', background: '#fff', borderRadius: 12, overflow: 'hidden', boxShadow: '0 1px 4px rgba(0,0,0,0.08)' },
    dTh: { padding: '12px 16px', textAlign: 'left', background: '#f8fafc', color: '#64748b', fontSize: 13, fontWeight: 600, borderBottom: '1px solid #e2e8f0' },
    dTd: { padding: '12px 16px', borderBottom: '1px solid #f1f5f9', fontSize: 14 },
    dSearchInput: { width: '100%', padding: '10px 16px', border: '1px solid #e2e8f0', borderRadius: 8, fontSize: 15, boxSizing: 'border-box', marginBottom: 16 },
    dSidebarTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 16, paddingBottom: 12, borderBottom: '1px solid rgba(255,255,255,0.2)' },
    dSidebarSection: { fontSize: 12, color: 'rgba(255,255,255,0.6)', marginTop: 16, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 },
    dFilterBtn: { width: '100%', textAlign: 'left', padding: '8px 12px', borderRadius: 8, border: 'none', background: 'transparent', color: '#fff', cursor: 'pointer', fontSize: 14 },
    dFilterBtnActive: { background: 'rgba(255,255,255,0.2)' },
    dBtnPrimary: { background: '#1e40af', color: '#fff', border: 'none', borderRadius: 8, padding: '10px 20px', fontSize: 14, cursor: 'pointer' },
    dBtnDanger: { background: '#dc2626', color: '#fff', border: 'none', borderRadius: 6, padding: '4px 10px', fontSize: 12, cursor: 'pointer' },
    dBtnDelete: { background: 'transparent', border: 'none', fontSize: 16, cursor: 'pointer' },
    dBadge: { fontSize: 11, padding: '2px 8px', borderRadius: 10, fontWeight: 500 },
    dLogoutBtn: { marginTop: 'auto', padding: '8px 12px', background: 'rgba(255,255,255,0.1)', border: 'none', color: '#fff', borderRadius: 8, cursor: 'pointer', fontSize: 14 },
    dStatsRow: { display: 'flex', gap: 16, marginBottom: 24 },
    dStatCard: { flex: 1, background: '#fff', borderRadius: 12, padding: '16px 20px', boxShadow: '0 1px 4px rgba(0,0,0,0.08)' },
    dStatNum: { fontSize: 32, fontWeight: 'bold', color: '#1e40af' },
    dStatLabel: { fontSize: 13, color: '#64748b', marginTop: 4 },
    loginContainer: { display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', background: '#f5f5f5' },
    loginBox: { background: '#fff', borderRadius: 16, padding: 32, width: 340, textAlign: 'center', boxShadow: '0 4px 20px rgba(0,0,0,0.1)' },
    header: { background: '#1e40af', color: '#fff', padding: '12px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'sticky', top: 0, zIndex: 10 },
    filters: { display: 'flex', gap: 8, padding: '8px 16px', overflowX: 'auto', background: '#fff', borderBottom: '1px solid #eee' },
    filterBtn: { padding: '4px 12px', borderRadius: 20, border: '1px solid #ddd', background: '#f5f5f5', cursor: 'pointer', whiteSpace: 'nowrap', fontSize: 13 },
    filterBtnActive: { background: '#1e40af', color: '#fff', border: '1px solid #1e40af' },
    list: { padding: 12, display: 'flex', flexDirection: 'column', gap: 10 },
    card: { borderRadius: 12, padding: 14, boxShadow: '0 1px 4px rgba(0,0,0,0.08)' },
    cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
    cardCode: { fontWeight: 'bold', fontSize: 15 },
    cardDesc: { fontSize: 13, color: '#444', marginBottom: 4 },
    cardSub: { fontSize: 12, color: '#666' },
    cardDate: { fontSize: 11, color: '#999', marginTop: 2 },
    cardActions: { display: 'flex', gap: 8, marginTop: 10, alignItems: 'center' },
    badge: { fontSize: 11, padding: '2px 8px', borderRadius: 10, fontWeight: 500 },
    btnPrimary: { background: '#1e40af', color: '#fff', border: 'none', borderRadius: 8, padding: '12px 24px', fontSize: 16, cursor: 'pointer', flex: 1 },
    btnSecondary: { background: '#e5e7eb', color: '#333', border: 'none', borderRadius: 8, padding: '12px 24px', fontSize: 16, cursor: 'pointer' },
    btnDanger: { background: '#dc2626', color: '#fff', border: 'none', borderRadius: 8, padding: '6px 12px', fontSize: 13, cursor: 'pointer' },
    btnDelete: { background: 'transparent', border: 'none', fontSize: 18, cursor: 'pointer', marginLeft: 'auto' },
    btnDisabled: { background: '#9ca3af', color: '#fff', border: 'none', borderRadius: 8, padding: '12px 24px', fontSize: 16, flex: 1 },
    btnIcon: { background: 'rgba(255,255,255,0.2)', color: '#fff', border: 'none', borderRadius: 8, padding: '6px 10px', fontSize: 16, cursor: 'pointer' },
    fab: { position: 'fixed', bottom: 24, left: '50%', transform: 'translateX(-50%)', background: '#1e40af', color: '#fff', border: 'none', borderRadius: 24, padding: '14px 28px', fontSize: 16, cursor: 'pointer', boxShadow: '0 4px 12px rgba(0,0,0,0.3)', zIndex: 100 },
    center: { textAlign: 'center', padding: 40, color: '#999' },
    input: { width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 8, fontSize: 16, marginBottom: 16, boxSizing: 'border-box' },
    textarea: { width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 8, fontSize: 14, marginBottom: 16, boxSizing: 'border-box', resize: 'vertical' },
    select: { width: '100%', padding: 12, border: '1px solid #ddd', borderRadius: 8, fontSize: 16, marginBottom: 16, background: '#fff', boxSizing: 'border-box' },
    label: { display: 'block', fontWeight: 600, marginBottom: 6, color: '#333' },
    qtyRow: { display: 'flex', alignItems: 'center', gap: 16, marginBottom: 24 },
    qtyBtn: { width: 40, height: 40, borderRadius: 20, border: '1px solid #ddd', background: '#f5f5f5', fontSize: 20, cursor: 'pointer' },
    qtyNum: { fontSize: 24, fontWeight: 'bold', minWidth: 40, textAlign: 'center' },
    actionRow: { display: 'flex', gap: 12, marginTop: 8 },
    sectionBadge: { background: '#dbeafe', color: '#1e40af', padding: '6px 12px', borderRadius: 8, fontSize: 13, fontWeight: 500 },
    codeDisplay: { fontSize: 20, fontWeight: 'bold', padding: '16px 0', color: '#111' },
    warning: { background: '#fef3c7', padding: 12, borderRadius: 8, color: '#92400e', marginBottom: 16 },
    error: { background: '#fee2e2', padding: 12, borderRadius: 8, color: '#dc2626', marginBottom: 16, fontSize: 14 },
  };