export const S = {
  // Mobile
  mContainer: { maxWidth: 480, margin: '0 auto', minHeight: '100vh', background: '#f8fafc', paddingBottom: 80 },

  // Desktop
  dLayout: { display: 'flex', minHeight: '100vh', background: '#f1f5f9' },
  dSidebar: { width: 260, background: '#1e293b', color: '#fff', padding: '24px 16px 24px 16px', display: 'flex', flexDirection: 'column', gap: 8, position: 'fixed', top: 0, left: 0, height: '100vh', overflowY: 'auto' },
  dMain: { marginLeft: 260, flex: 1, padding: 24 },
  dHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  dTitle: { fontSize: 24, fontWeight: 'bold', color: '#0f172a' },
  dTable: { width: '100%', borderCollapse: 'collapse', background: '#fff', borderRadius: 12, overflow: 'hidden', boxShadow: '0 1px 4px rgba(0,0,0,0.08)' },
  dTh: { padding: '12px 16px', textAlign: 'left', background: '#1e293b', color: '#94a3b8', fontSize: 13, fontWeight: 600, borderBottom: '1px solid #334155' },
  dTd: { padding: '12px 16px', borderBottom: '1px solid #f1f5f9', fontSize: 14, transition: 'background 0.2s' },
  dSearchInput: { width: '100%', padding: '10px 16px', border: '1px solid #e2e8f0', borderRadius: 8, fontSize: 15, boxSizing: 'border-box', marginBottom: 16, background: '#fff' },
  dSidebarTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 16, paddingBottom: 12, borderBottom: '1px solid #334155', color: '#84cc16' },
  dSidebarSection: { fontSize: 11, color: '#64748b', marginTop: 16, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 },
  dFilterBtn: { width: '100%', textAlign: 'left', padding: '8px 12px', borderRadius: 8, border: 'none', background: 'transparent', color: '#cbd5e1', cursor: 'pointer', fontSize: 14, transition: 'all 0.2s' },
  dFilterBtnActive: { background: '#84cc16', color: '#0f172a', fontWeight: 600 },
  dBtnPrimary: { background: '#84cc16', color: '#0f172a', border: 'none', borderRadius: 8, padding: '10px 20px', fontSize: 14, cursor: 'pointer', fontWeight: 600, transition: 'all 0.2s' },
  dBtnDanger: { background: '#dc2626', color: '#fff', border: 'none', borderRadius: 6, padding: '4px 10px', fontSize: 12, cursor: 'pointer', transition: 'all 0.2s' },
  dBtnDelete: { background: 'transparent', border: 'none', fontSize: 16, cursor: 'pointer', transition: 'all 0.2s' },
  dBadge: { fontSize: 11, padding: '2px 8px', borderRadius: 10, fontWeight: 500 },
  dLogoutBtn: { padding: '8px 12px', background: '#334155', border: 'none', color: '#cbd5e1', borderRadius: 8, cursor: 'pointer', fontSize: 14, transition: 'all 0.2s', textAlign: 'left', width: '100%' },
  dStatsRow: { display: 'flex', gap: 16, marginBottom: 24 },
  dStatCard: { flex: 1, background: '#fff', borderRadius: 12, padding: '16px 20px', boxShadow: '0 1px 4px rgba(0,0,0,0.08)', borderLeft: '4px solid #84cc16' },
  dStatNum: { fontSize: 32, fontWeight: 'bold', color: '#0f172a' },
  dStatLabel: { fontSize: 13, color: '#64748b', marginTop: 4 },

  // Shared
  loginContainer: { display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', background: '#0f172a' },
  loginBox: { background: '#1e293b', borderRadius: 16, padding: 32, width: 340, textAlign: 'center', boxShadow: '0 4px 20px rgba(0,0,0,0.4)' },
  header: { background: '#1e293b', color: '#fff', padding: '12px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', position: 'sticky', top: 0, zIndex: 10 },
  filters: { display: 'flex', gap: 8, padding: '8px 16px', overflowX: 'auto', background: '#fff', borderBottom: '1px solid #eee' },
  filterBtn: { padding: '4px 12px', borderRadius: 20, border: '1px solid #ddd', background: '#f5f5f5', cursor: 'pointer', whiteSpace: 'nowrap', fontSize: 13, transition: 'all 0.2s' },
  filterBtnActive: { background: '#84cc16', color: '#0f172a', border: '1px solid #84cc16', fontWeight: 600 },
  list: { padding: 12, display: 'flex', flexDirection: 'column', gap: 10 },
  card: { borderRadius: 12, padding: 14, boxShadow: '0 1px 4px rgba(0,0,0,0.08)', transition: 'transform 0.2s, box-shadow 0.2s', animation: 'fadeIn 0.3s ease' },
  cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  cardCode: { fontWeight: 'bold', fontSize: 15 },
  cardDesc: { fontSize: 13, color: '#444', marginBottom: 4 },
  cardSub: { fontSize: 12, color: '#666' },
  cardDate: { fontSize: 11, color: '#999', marginTop: 2 },
  cardActions: { display: 'flex', gap: 8, marginTop: 10, alignItems: 'center' },
  badge: { fontSize: 11, padding: '2px 8px', borderRadius: 10, fontWeight: 500 },
  btnPrimary: { background: '#84cc16', color: '#0f172a', border: 'none', borderRadius: 8, padding: '12px 24px', fontSize: 16, cursor: 'pointer', flex: 1, fontWeight: 600, transition: 'all 0.2s' },
  btnSecondary: { background: '#334155', color: '#fff', border: 'none', borderRadius: 8, padding: '12px 24px', fontSize: 16, cursor: 'pointer', transition: 'all 0.2s' },
  btnDanger: { background: '#dc2626', color: '#fff', border: 'none', borderRadius: 8, padding: '6px 12px', fontSize: 13, cursor: 'pointer', transition: 'all 0.2s' },
  btnDelete: { background: 'transparent', border: 'none', fontSize: 18, cursor: 'pointer', marginLeft: 'auto' },
  btnDisabled: { background: '#475569', color: '#94a3b8', border: 'none', borderRadius: 8, padding: '12px 24px', fontSize: 16, flex: 1 },
  btnIcon: { background: 'rgba(132,204,22,0.2)', color: '#84cc16', border: 'none', borderRadius: 8, padding: '6px 10px', fontSize: 16, cursor: 'pointer', transition: 'all 0.2s' },
  fab: { position: 'fixed', bottom: 24, left: '50%', transform: 'translateX(-50%)', background: '#84cc16', color: '#0f172a', border: 'none', borderRadius: 24, padding: '14px 28px', fontSize: 16, cursor: 'pointer', boxShadow: '0 4px 12px rgba(132,204,22,0.4)', zIndex: 100, fontWeight: 600, transition: 'all 0.2s' },
  center: { textAlign: 'center', padding: 40, color: '#64748b' },
  input: { width: '100%', padding: 12, border: '1px solid #334155', borderRadius: 8, fontSize: 16, marginBottom: 16, boxSizing: 'border-box', background: '#0f172a', color: '#fff' },
  textarea: { width: '100%', padding: 12, border: '1px solid #334155', borderRadius: 8, fontSize: 14, marginBottom: 16, boxSizing: 'border-box', resize: 'vertical', background: '#0f172a', color: '#fff' },
  select: { width: '100%', padding: 12, border: '1px solid #334155', borderRadius: 8, fontSize: 16, marginBottom: 16, background: '#0f172a', color: '#fff', boxSizing: 'border-box' },
  label: { display: 'block', fontWeight: 600, marginBottom: 6, color: '#cbd5e1' },
  qtyRow: { display: 'flex', alignItems: 'center', gap: 16, marginBottom: 24 },
  qtyBtn: { width: 40, height: 40, borderRadius: 20, border: '1px solid #334155', background: '#1e293b', color: '#fff', fontSize: 20, cursor: 'pointer', transition: 'all 0.2s' },
  qtyNum: { fontSize: 24, fontWeight: 'bold', minWidth: 40, textAlign: 'center', color: '#fff' },
  actionRow: { display: 'flex', gap: 12, marginTop: 8 },
  sectionBadge: { background: 'rgba(132,204,22,0.2)', color: '#84cc16', padding: '6px 12px', borderRadius: 8, fontSize: 13, fontWeight: 500 },
  codeDisplay: { fontSize: 20, fontWeight: 'bold', padding: '16px 0', color: '#84cc16' },
  warning: { background: '#422006', padding: 12, borderRadius: 8, color: '#fbbf24', marginBottom: 16 },
  error: { background: '#450a0a', padding: 12, borderRadius: 8, color: '#fca5a5', marginBottom: 16, fontSize: 14 },
};